//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealineMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class LienHe
    {
        public int Id { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string NoiDung { get; set; }
        public LienHe(int idLh)
        {
            using(QuanLyBanHangEntities3 db = new QuanLyBanHangEntities3())
            {
                this.Id = idLh;
                LienHe lh = db.LienHes.Single(n => n.Id == idLh);
                this.HoTen = lh.HoTen;
                this.Email = lh.Email;
                this.NoiDung = lh.NoiDung;

            }
        }
        public LienHe() { }
    }
}
