//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealineMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.ChiTietDonDatHangs = new HashSet<ChiTietDonDatHang>();
            this.ChiTietPhieuNhaps = new HashSet<ChiTietPhieuNhap>();
        }
        public SanPham(int maSP)
        {
            using (QuanLyBanHangEntities3 db = new QuanLyBanHangEntities3())
            {
                this.MaSP = maSP;
                SanPham model = db.SanPhams.Single(n => n.MaSP == maSP);
                this.TenSP = model.TenSP;
                this.DonGia = model.DonGia;
                this.NgayCapNhat = model.NgayCapNhat;
                this.CauHinh = CauHinh;
                this.MoTa = MoTa;
                this.SoLuongTon = SoLuongTon;
                this.LuotXem = LuotXem;
                this.LuotBinhChon = LuotBinhChon;
                this.LuotBinhLuan = LuotBinhLuan;
                this.SoLanMua = SoLanMua;
                this.Moi = Moi;
                this.MaNCC = MaNCC;
                this.MaNSX = MaNSX;
                this.MaLoaiSP = MaLoaiSP;
                this.DaXoa = DaXoa;
                this.HinhAnh = HinhAnh;
                this.HinhAnh1 = HinhAnh1;
                this.HinhAnh2 = HinhAnh2;
                this.HinhAnh3 = HinhAnh3;
                this.HinhAnh4 = HinhAnh4;

            }
        }
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string CauHinh { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> LuotBinhChon { get; set; }
        public Nullable<int> LuotBinhLuan { get; set; }
        public Nullable<int> SoLanMua { get; set; }
        public Nullable<int> Moi { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public Nullable<int> MaNSX { get; set; }
        public Nullable<int> MaLoaiSP { get; set; }
        public Nullable<int> DaXoa { get; set; }
        public string HinhAnh { get; set; }
        public string HinhAnh1 { get; set; }
        public string HinhAnh2 { get; set; }
        public string HinhAnh3 { get; set; }
        public string HinhAnh4 { get; set; }
        public string hung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhaSanXuat NhaSanXuat { get; set; }
    }
}
